import { customType } from "drizzle-orm/pg-core";

/**
 * Postgres `tsvector`, which Drizzle has no built-in column type for.
 *
 * `customType` only needs to answer one question — what DDL type name to emit.
 * The values are read back as strings; we never construct one in TypeScript,
 * because the column is generated by Postgres itself.
 */
export const tsvector = customType<{ data: string; driverData: string }>({
  dataType() {
    return "tsvector";
  },
});
