import { NextResponse, type NextRequest } from "next/server";
import { z } from "zod";

import { getCurrentUser } from "@/features/auth/auth.session";
import { createSignedRead } from "@/integrations/storage/storage.client";
import { StorageError } from "@/integrations/storage/storage.types";

const querySchema = z.object({
  key: z.string().min(1).max(500),
});

/** Issue a fresh credential when an image outlives its server-rendered URL. */
export async function GET(request: NextRequest) {
  const user = await getCurrentUser();

  if (!user) {
    return NextResponse.json({ error: "Not signed in." }, { status: 401 });
  }

  const parsed = querySchema.safeParse({
    key: request.nextUrl.searchParams.get("key"),
  });

  // Storage keys are generated by the app and always begin with their owner's
  // branded user id. A foreign key and a missing key intentionally look alike.
  if (!parsed.success || !parsed.data.key.startsWith(`${user.id}/`)) {
    return NextResponse.json({ error: "Image not found." }, { status: 404 });
  }

  try {
    const signed = await createSignedRead(parsed.data.key);
    return NextResponse.json(
      { url: signed.url },
      { headers: { "Cache-Control": "private, no-store" } },
    );
  } catch (error) {
    if (error instanceof StorageError) {
      return NextResponse.json(
        { error: "Storage is not responding." },
        { status: 502 },
      );
    }

    throw error;
  }
}
