import type { pages } from "@/db/schema";
import type { BookId } from "@/db/ids";

type Point = { x: number; y: number };

export type Page = typeof pages.$inferSelect;

export type NewPage = {
  bookId: BookId;
  pageNumber: number;
  /** Path inside the private bucket. Not a URL — signed URLs expire. */
  storageKey: string;
  /** Intrinsic dimensions of the uploaded image, in pixels. */
  imageWidth: number;
  imageHeight: number;
  /** Generated by the server after the upload; null when generation failed. */
  thumbnailStorageKey: string | null;
  /** The unflattened photograph, when the processor replaced it. */
  originalStorageKey: string | null;
  /** The corners the reader placed, when they placed any. */
  pageCorners: [Point, Point, Point, Point] | null;
};
